.env.example
config/settings/base.py
config/settings/local.py
core/urls.py
core/views.py
poetry.lock
pyproject.toml

Integrated sentry to enable real-time error and performance monitoring / reporting:
- Added sentry-sdk and configured sentry.
- Tested error capturing on local as we haven't done a deployment yet. (https://sentry.ci.uktrade.digital/organizations/dit/projects/identity/?project=262)
To do:
- Verify error capture works on all environments.
-  Add environment variables for sentry to AWS parameter store and to `identity-deploy` repo.
-  Remove `sentry-debug` endpoint after verifying all environments work.
- Remove `local` env from sentry.

IDPF-91 Setup sentry integration

---

.github/workflows/ci.yml

Updating "Build and test" workflow to run on push to main.

IDPF-113 Trigger ci on push to main

---

Procfile
poetry.lock
pyproject.toml

IDPF-115 Replacing Waitress with Granian

---

.copilot/config.yml
.copilot/image_build_run.sh

Added the copilot config to the project to allow building in AWS 🤞.

IDPF-92 Added copilot config

---

.copilot/config.yml
.copilot/image_build_run.sh

This is a update to the builder image, swapping out `paketobuildpacks/builder-jammy-full` to `paketobuildpacks/builder-jammy-base` as suggested by SRE.

IDPF-92 Update Builder Image

---

.copilot/config.yml
.copilot/image_build_run.sh
Procfile

Updated the paketo builder to use the full version to try and resolve missing cpython files.

IDPF-92 Updated Paketo builder

---

Procfile

IDPF-121 updated granian worker count to 1 by default

---

makefile

IDPF-122 Add make command for running granian on local

---

config/settings/developer.py
docker-compose.yml

added config for running locally

---

config/settings/base.py
user/backends.py

Adds a custom backend to the project that overrides the create user mapping from Staff SSO Client's AuthbrokerBackend.

IDPF-174 Custom AuthBackend to override user_create_mapping

---

.env.example
README.md
config/settings/base.py
docker-compose.yml
manage.py
poetry.lock
pyproject.toml

Debugpy setup

---

.copilot/config.yml
pyproject.toml

Trying to fix it so poetry install works without hurting paketo deploy

Fix poetry install and deploy issue

---

core/services.py
core/tests/test_services.py
scim/api.py
scim/schemas/__init__.py

IDPF-203 Create the DELETE users SCIM endpoint

---

core/services.py
core/tests/test_services.py
profiles/services/__init__.py
profiles/services/combined.py
profiles/services/staff_sso.py
profiles/tests/test_services_staff_sso.py

1. Delete profile from database implemented with tests
2. Core Services delete identity implemented with tests

IDPF-209: Create staff sso service delete function

---

scim/api.py

Quick fix to use core_services.get_by_id instead of profile_services.get_by_id

Use core_services.get_by_id

---

config/settings/base.py
config/settings/developer.py
docker-compose.yml

Please feel free to further improve this; I was going crazy with all the ASIM stuff. I'm not sure this is logging enough any more, and I don't know how to stop the tracer (my dockerfile env doesn't seem to be working?)

Friendlier local logging

---

config/settings/developer.py
core/api/scim.py

The routes have a try/catch in place but it's not covering all possible exceptions that we are **expecting**.
ie. `User.DoesNotExist` & `ValueError`, both have custom responses (400's), but I don't think these are actually being called, instead the Service is returning a 500 response to the client.
Refactored what sits inside the try/catch to catch these errors under the correct status codes.
* Also contains a change to `Developer.py` to allow local running both SSO & Identity at the same time, optional will remove if we don't want it.

IDPF-235 Update the SCIM API to handle exceptions correctly.

---

.github/workflows/e2e.yml

FE build seems to be missing / not working in e2e

Attempt to solve e2e issues 

---

config/settings/base.py
config/settings/developer.py

I broke local dev with my conditional logic, List.remove() doesn't like it when you try to remove something that doesn't exist. 😢

IDPF-249 Fix local dev

---

Procfile

Start dd agent at runtime

---

user/admin.py

IDPF-270: added bulk sync ID with sso to Django Admin page

---

config/settings/prod.py

Exempt healthcheck URL from SSL redirect

---

config/settings/prod.py

fix broken HC regex

---

config/settings/prod.py

Formatting fix

---

core/schemas/scim.py

IDPF-220: fixed email addresses not being returned in MinimalUserResponse

---

core/api/people_finder.py
core/schemas/peoplefinder.py
core/services.py
profiles/admin.py
profiles/services/__init__.py

IDPF-294: get people finder profile api endpoint

---

conftest.py
core/api/people_finder.py
core/schemas/profiles.py
core/services.py
profiles/services/__init__.py
profiles/services/peoplefinder.py
profiles/tests/test_services_peoplefinder.py

This PR adds a new endpoint to get all uk staff locations.

IDPF-306 Create UKStaffLocation endpoint

---

core/api/people_finder.py
core/schemas/peoplefinder.py
core/services.py
profiles/services/__init__.py
profiles/services/peoplefinder.py
profiles/tests/test_services_peoplefinder.py

IDPF-305: People finder Country endpoint

---

.github/pull_request_template.md

Experimental update to pull request template

---

package-lock.json
package.json

IDPF-360: Upgrading esbuild and vite to fix security vulnerability

---

core/api/people_finder.py
core/services.py
docs/apis/people-finder.md
e2e_tests/test_peoplefinder.py
profiles/services/__init__.py
profiles/services/peoplefinder.py
profiles/tests/test_services_peoplefinder.py

IDPF-307: Added learning interest api

---

core/api/people_finder.py
core/services.py
docs/apis/people-finder.md
e2e_tests/test_peoplefinder.py
profiles/services/__init__.py
profiles/services/peoplefinder.py
profiles/tests/test_services_peoplefinder.py

Adds professions endpoint to `peoplefinder` api `/reference/professions/`

IDPF-304 Create professions endpoint

---

profiles/services/combined.py
profiles/services/staff_sso.py

IDPF-362: adding validation before create and save of sso profile

---

conftest.py
profiles/services/peoplefinder.py
profiles/tests/test_services_peoplefinder.py

IDPF-363: added validation to people finder profile create and update services

---

conftest.py
e2e_tests/test_peoplefinder.py
user/services.py

IDPF-365: Added validation to user profile create and update services

---

core/api/people_finder.py
core/services.py
docs/apis/people-finder.md
e2e_tests/test_peoplefinder.py
profiles/services/__init__.py
profiles/services/peoplefinder.py
profiles/tests/test_services_peoplefinder.py

Added additional roles endpoint.

IDPF-309 Added additional roles

---

config/settings/base.py

Fixed the Redis url, as Parameter store keeps reseting the value

IDPF-374 Fix Redis url

---

config/settings/prod.py

Added a default value to AWS_S3_CUSTOM_DOMAIN, to hopefully allow deployment to run. 🤞

IDPF-384 Added default value for AWS_S3_CUSTOM_DOMAIN

---

core/api/__init__.py

PEN TEST WORKAROUND: remove auth on staging

---

config/settings/base.py
core/middleware.py

IDPF-416: Add no-cache headers to all responses

---

.github/workflows/e2e.yml

Update python version to 3.13 for e2e-tests

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/e2e.yml

Fix code scan issue - add permissions to github workflows
